// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lihkydwqjbriyfioromz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpaGt5ZHdxamJyaXlmaW9yb216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDkzMDAsImV4cCI6MjA1ODk4NTMwMH0.yz3aoGqG6hcWx27ryTsY2y4bsEPWOmY1nu82KUg_aZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);